//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fractron9000.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Narratives {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Narratives() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fractron9000.UI.Narratives", typeof(Narratives).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Failed::Program Compilation Failed:
        ///{0}.
        /// </summary>
        internal static string Error_BuildFailed {
            get {
                return ResourceManager.GetString("Error_BuildFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Failed::Your CUDA version appears to be out of date. Please ensure you have the latest video drivers installed and try again..
        /// </summary>
        internal static string Error_CudaVersionFail {
            get {
                return ResourceManager.GetString("Error_CudaVersionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLL Not Found::A required .dll file could not be found. Please try reinstalling Fractron 9000. Please also ensure you have the latest drivers installed for your video card..
        /// </summary>
        internal static string Error_DllNotFound {
            get {
                return ResourceManager.GetString("Error_DllNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractal Engine Error::Uh-oh, the rendering engine has crashed. This may be caused by invalid settings, or possibly a bug..
        /// </summary>
        internal static string Error_EngineCycle {
            get {
                return ResourceManager.GetString("Error_EngineCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Failed::The fractal engine could not start.
        ///Please try the following:
        ///
        ///1. Make sure you have Microsoft&apos;s .NET Framework 2.0 installed. It can be downloaded for free at:
        ///http://www.microsoft.com/downloads/details.aspx?familyid=0856eacb-4362-4b0d-8edd-aab15c5e04f5&amp;displaylang=en
        ///
        ///2. Make sure you have the latest drivers for your video card.
        ///Nvidia drivers can be downloaded at: http://www.nvidia.com/Download/index.aspx?lang=en-us
        ///AMD/ATI drivers can be downloaded at: http://support.amd.com/us/g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Error_EngineStartupFail {
            get {
                return ResourceManager.GetString("Error_EngineStartupFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Load Failed::Could not open the .flame library file &quot;{0}&quot;..
        /// </summary>
        internal static string Error_FlameLoadFailed {
            get {
                return ResourceManager.GetString("Error_FlameLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Save Failed::Could not save the .flame library file to &quot;{0}&quot;..
        /// </summary>
        internal static string Error_FlameSaveFailed {
            get {
                return ResourceManager.GetString("Error_FlameSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractal Load Failed::The fractal file failed to open. The file may be corrupt..
        /// </summary>
        internal static string Error_FractalOpenFailed {
            get {
                return ResourceManager.GetString("Error_FractalOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Save Failed::Could not save image &quot;{0}&quot;..
        /// </summary>
        internal static string Error_ImageSaveFailed {
            get {
                return ResourceManager.GetString("Error_ImageSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Configuration Failed::Failed to perform initial configuration. Attempting to continue..
        /// </summary>
        internal static string Error_InitConfigLoadFailed {
            get {
                return ResourceManager.GetString("Error_InitConfigLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Compatible Hardware Found::Fractron 9000 couldn&apos;t find any compatable rendering devices. Make sure you have the latest video drivers installed. Click on &quot;Help&quot; -&gt; &quot;Hardware Info&quot; for details..
        /// </summary>
        internal static string Error_NoDevicesFound {
            get {
                return ResourceManager.GetString("Error_NoDevicesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required OpenGL Version Not Found::Fractron 9000 requires {0} version {1} or higher. The currently installed version is version {2}. Updating your video card drivers may solve this problem. .
        /// </summary>
        internal static string Error_OpenGLVersion {
            get {
                return ResourceManager.GetString("Error_OpenGLVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Video Memory::Uh-oh, it looks like Fractron 9000 has run out of video memory. To fix this, open the Configuration dialog from the Edit menu and try lowering the custom output resolution. Closing the program and restarting may also help..
        /// </summary>
        internal static string Error_OutOfMemory {
            get {
                return ResourceManager.GetString("Error_OutOfMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error::An unknown error has occured..
        /// </summary>
        internal static string Error_Unknown {
            get {
                return ResourceManager.GetString("Error_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractron 9000 is a high performance fractal flame renderer. Fractron 9000 takes advantage of modern programmable graphics processors to dramatically speed up rendering.
        ///
        ///Currently, Fractron 9000 supports rendering through OpenCL, NVidia CUDA, and OpenGL 2.0..
        /// </summary>
        internal static string Info_Description {
            get {
                return ResourceManager.GetString("Info_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version..
        /// </summary>
        internal static string Info_LicenseBrief {
            get {
                return ResourceManager.GetString("Info_LicenseBrief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just a test.
        /// </summary>
        internal static string TestMessage {
            get {
                return ResourceManager.GetString("TestMessage", resourceCulture);
            }
        }
    }
}
