//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fractron9000 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefaultFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fractron9000.DefaultFiles", typeof(DefaultFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] Flames_My_Fractals {
            get {
                object obj = ResourceManager.GetObject("Flames_My_Fractals", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Flames_Sample_Fractals {
            get {
                object obj = ResourceManager.GetObject("Flames_Sample_Fractals", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		    GNU GENERAL PUBLIC LICENSE
        ///		       Version 2, June 1991
        ///
        /// Copyright (C) 1989, 1991 Free Software Foundation, Inc.,
        /// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///			    Preamble
        ///
        ///  The licenses for most software are designed to take away your
        ///freedom to share and change it.  By contrast, the GNU General Public
        ///License is intended to guarantee your freedom  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;Fractron 9000 Manual&lt;/title&gt;
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///body{
        ///  color: #FFFFFF;
        ///  background-color: #000000;
        ///  font-family: Sans-serif;
        ///}
        ///a:link,a:active,a:hover{
        ///  color: #80C0FF;
        ///}
        ///a:visited{
        ///  color: #4080C0;
        ///}
        ///
        ///a img{
        ///  border-style: none;
        ///}
        ///
        ///ul, p{
        ///  margin: 0.2em 0.0em 0.5em 0.0em;
        ///}
        ///
        ///h2{
        ///  margin: 0.0em 0.0em 0.0em 0.0em;
        ///  padding: 0.0em 0.0em 0.0em 0.0em;
        ///}
        ///
        ///#heading{
        ///  width: 100%;
        ///  margin: 0px;
        ///  padding: 0px;
        ///  border-spacing: 0px;
        ///  backgroun [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Palette_dark {
            get {
                object obj = ResourceManager.GetObject("Palette_dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Palette_default {
            get {
                object obj = ResourceManager.GetObject("Palette_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Palette_frost {
            get {
                object obj = ResourceManager.GetObject("Palette_frost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Palette_inferno2 {
            get {
                object obj = ResourceManager.GetObject("Palette_inferno2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
